# Generated by Django 6.0.4 on 2026-04-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
